[package]
name = "digital_thermometer_controller"
version = "0.3.0"
authors = ["Kazakov Giorgi Vladimirovich", "Sidorov Roman Alexandrovich"]
edition = "2024"

[[bin]]
name = "digital_thermometer_controller"
harness = false # do not use the built in cargo test harness -> resolve rust-analyzer errors

[dependencies]
anyhow = "1.0.97"
esp-idf-svc = { version = "0.51.0", features = ["critical-section", "embassy-time-driver", "embassy-sync"] }
heapless = "0.9.2"
log = "0.4.29"
thermometer = { git = "https://github.com/ippras-blca/thermometer", branch = "update" }
thiserror = "2.0.18"
tokio = { version = "1.49.0", features = ["rt", "net", "time", "io-util", "macros"] }
tokio-modbus = { version = "0.17.0", features = ["tcp-server"] }

# bincode = "2.0.1"
# async-channel = "2.3.1"
# ron = "0.9.0"
# led = { git = "https://github.com/ippras-blca/led" }

[build-dependencies]
embuild = "0.33.1"

[features]
default = []

experimental = ["esp-idf-svc/experimental"]

[profile.release]
opt-level = "s"

[profile.dev]
debug = true    # Symbols are nice and they don't increase the size on Flash
opt-level = "z"
